# Generated by Django 4.2.2 on 2023-09-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('accounting_period', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='会計期')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '会計期間マスター',
                'ordering': ['-accounting_period'],
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('accounting_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.accountingperiod', verbose_name='会計期')),
            ],
            options={
                'verbose_name_plural': '所属マスター',
                'ordering': ['department__display_order', 'position__display_order', 'grade__display_order'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='取引先名')),
                ('client_name_s', models.CharField(blank=True, max_length=20, null=True, verbose_name='取引先略称')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '取引先マスター',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='部門コード')),
                ('department_name', models.CharField(max_length=50, verbose_name='部門名')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '部門マスター',
                'ordering': ['-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=6, verbose_name='社員番号')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('employee_code', models.CharField(max_length=100, verbose_name='社員コード')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='退職日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '社員マスター',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='資格コード')),
                ('grade_name', models.CharField(max_length=50, verbose_name='資格名')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '資格マスター',
                'ordering': ['-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='仕入先名')),
                ('partner_name', models.CharField(max_length=100, verbose_name='パートナー名')),
                ('partner_name_k', models.CharField(blank=True, max_length=100, null=True, verbose_name='パートナー名(カナ)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': 'パートナーマスター',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='役職コード')),
                ('position_name', models.CharField(max_length=50, verbose_name='役職名')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '役職マスター',
                'ordering': ['-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost1', models.IntegerField(default=0, verbose_name='労務費')),
                ('cost2', models.IntegerField(default=0, verbose_name='通勤費')),
                ('cost3', models.IntegerField(default=0, verbose_name='間接労務費')),
                ('cost4', models.IntegerField(default=0, verbose_name='間接費配賦見込')),
                ('cost_total', models.IntegerField(default=0, verbose_name='概算原価')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.affiliation', verbose_name='所属')),
            ],
            options={
                'verbose_name_plural': '概算原価マスター',
                'ordering': ['-updated'],
            },
        ),
        migrations.AddField(
            model_name='affiliation',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.department', verbose_name='部門'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee', verbose_name='氏名'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.grade', verbose_name='資格'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.position', verbose_name='役職'),
        ),
    ]
