# Generated by Django 4.2.2 on 2023-09-11 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_period', models.SmallIntegerField(verbose_name='会計期')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '会計期間マスター',
                'ordering': ['-accounting_period'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='部門名')),
                ('department_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='部門コード')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '部門マスター',
                'ordering': ['-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=6, verbose_name='社員番号')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('employee_code', models.CharField(max_length=100, verbose_name='社員コード')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入社日')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='退職日')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '社員マスター',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50, verbose_name='資格名')),
                ('grade_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='資格コード')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '資格マスター',
                'ordering': ['-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, verbose_name='役職名')),
                ('position_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='役職コード')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '役職マスター',
                'ordering': ['-display_order'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost1', models.IntegerField(default=0, verbose_name='労務費')),
                ('cost2', models.IntegerField(default=0, verbose_name='通勤費')),
                ('cost3', models.IntegerField(default=0, verbose_name='間接労務費')),
                ('cost4', models.IntegerField(default=0, verbose_name='間接費配賦見込')),
                ('cost_total', models.IntegerField(default=0, verbose_name='概算原価')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('accounting_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.accountingperiod', verbose_name='会計期')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee', verbose_name='社員')),
            ],
            options={
                'verbose_name_plural': '概算原価マスター',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('accounting_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.accountingperiod', verbose_name='会計期')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.department', verbose_name='部門')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee', verbose_name='氏名')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.grade', verbose_name='資格')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.position', verbose_name='役職')),
            ],
            options={
                'verbose_name_plural': '所属マスター',
            },
        ),
    ]
