# Generated by Django 4.2.2 on 2023-09-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='取引先名')),
                ('client_name_s', models.CharField(max_length=20, verbose_name='取引先略称')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': '取引先マスター',
                'ordering': ['-updated'],
            },
        ),
    ]
