# Generated by Django 4.2.2 on 2023-09-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_accountingperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost1', models.IntegerField(default=0, verbose_name='労務費')),
                ('cost2', models.IntegerField(default=0, verbose_name='通勤費')),
                ('cost3', models.IntegerField(default=0, verbose_name='間接労務費')),
                ('cost4', models.IntegerField(default=0, verbose_name='間接費配賦見込')),
                ('cost_total', models.IntegerField(default=0, verbose_name='概算原価')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('accounting_period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.accountingperiod', verbose_name='会計期')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee', verbose_name='社員')),
            ],
            options={
                'verbose_name_plural': '概算原価マスター',
                'ordering': ['-updated'],
            },
        ),
    ]
