# Generated by Django 4.2.2 on 2023-09-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name_s',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='取引先略称'),
        ),
    ]
