# Generated by Django 4.2.2 on 2023-09-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_client_client_name_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='accounting_period',
        ),
        migrations.RemoveField(
            model_name='cost',
            name='employee',
        ),
        migrations.AddField(
            model_name='cost',
            name='affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.affiliation', verbose_name='所属'),
        ),
    ]
