# Generated by Django 4.2.2 on 2023-09-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_cost_accounting_period_remove_cost_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='仕入先名')),
                ('partner_name', models.CharField(max_length=100, verbose_name='パートナー名')),
                ('partner_name_k', models.CharField(blank=True, max_length=100, null=True, verbose_name='パートナー名(カナ)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考')),
                ('display_order', models.CharField(default='00', max_length=2, verbose_name='表示順')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name_plural': 'パートナーマスター',
                'ordering': ['-updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ['department__display_order', 'position__display_order', 'grade__display_order'], 'verbose_name_plural': '所属マスター'},
        ),
    ]
